### ISSUE TITLE
Checklist for making repo public

### ISSUE THREAD

**Issue by rmatsum836** [mosdef-hub/mosdef_slitpore#9]
A checklist of things to do before making this repository public:

- [ ]  Improve the documentation via the README which includes installation instructions, simulation details, an overview of each simulation step, etc.

- [ ] Add a `requirements.txt` that allows a user to conda install or pip install dependencies for this package

- [ ] Test instructions for installation using a fresh environment to ensure everything runs properly
